lendinvest dev/force-app/main/default/objects/Account/fields/Customer_Classification__c.field-meta.xml
<CustomField>
    <fullName>Customer_Classification__c</fullName>
    <description>classifies the customer depending on total amount spent</description>
    <inlineHelpText>classifies the customer as follows: 
 ● GOLD = Total Customer Spend of £50,000 and above,
 ● SILVER = Total Customer Spend of £25,000 and above,
 ● BRONZE = Total Customer Spend of £10,000 and above, 
 ● &lt;blank&gt;= Total Customer Spend is less than £10,000, leave the field blank.</inlineHelpText>
    <label>Customer Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRONZE</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>&apos;&apos;</fullName>
                <default>true</default>
                <label>&apos;&apos;</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

lendinvest dev/force-app/main/default/objects/Account/fields/First_Time_Gold_Classification__c.field-meta.xml
<CustomField>
    <fullName>First_Time_Gold_Classification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>flag to know if it s the first time that the account reach the gold classification</description>
    <inlineHelpText>flag to know if it s the first time that the account reach the gold classification</inlineHelpText>
    <label>First Time Gold Classification</label>
    <type>Checkbox</type>
</CustomField>

lendinvest dev/force-app/main/default/objects/Account/fields/Total_Customer_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Customer_Spend__c</fullName>
    <description>the Sum of the Amount of closed-won opportunities for an Account.</description>
    <inlineHelpText>this field display the Sum of the Amount of closed-won opportunities for an Account.</inlineHelpText>
    <label>Total Customer Spend</label>
    <summarizedField>Opportunity.Amount</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

lendinvest dev/force-app/main/default/classes/TestCustomerClassificationUtil.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 12-28-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/

	@isTest
	private class TestCustomerClassificationUtil {
		@testSetup
		static void setup() {
			// Insert test accounts
			Account a1 = new Account(Name='Test Account 1', First_Time_Gold_Classification__c=false);
			Account a2 = new Account(Name='Test Account 2', First_Time_Gold_Classification__c=false);
			Account a3 = new Account(Name='Test Account 3', First_Time_Gold_Classification__c=false);
			Account a4 = new Account(Name='Test Account 4', First_Time_Gold_Classification__c=false);
			Account a5 = new Account(Name='Test Account 5', First_Time_Gold_Classification__c=false);
			Account a6 = new Account(Name='Test Account 6', First_Time_Gold_Classification__c=true);
			insert new Account[]{a1, a2, a3, a4, a5, a6};
	
		  // Insert test opportunities
		  Opportunity o1 = new Opportunity(Name='Test Opportunity 1', AccountId=a1.Id, Amount=50000, CloseDate=Date.today(), StageName='Closed Won');
		  Opportunity o2 = new Opportunity(Name='Test Opportunity 2', AccountId=a2.Id, Amount=25000, CloseDate=Date.today(), StageName='Closed Won');
		  Opportunity o3 = new Opportunity(Name='Test Opportunity 3', AccountId=a3.Id, Amount=10000, CloseDate=Date.today(), StageName='Closed Won');
		  Opportunity o4 = new Opportunity(Name='Test Opportunity 4', AccountId=a4.Id, Amount=5000, CloseDate=Date.today(), StageName='Closed Won');
		  Opportunity o5 = new Opportunity(Name='Test Opportunity 5', AccountId=a5.Id, Amount=0, CloseDate=Date.today(), StageName='Closed Won');
		  Opportunity o6 = new Opportunity(Name='Test Opportunity 6', AccountId=a6.Id, Amount=50000, CloseDate=Date.today(), StageName='Closed Won');
		  insert new Opportunity[]{o1, o2, o3, o4, o5, o6};

		}
		   
	
       

    @isTest
    static void testUpdateClassification() {
        test.startTest();

        // Retrieve test accounts
        List<Account> accounts = [SELECT Name, Total_Customer_Spend__c, First_Time_Gold_Classification__c, Customer_Classification__c FROM Account];

        // Update customer classifications
        CustomerClassificationUtil.updateClassification(accounts);

        // Check that customer classifications have been updated correctly
        for (Account a : accounts) {
            if (a.Name == 'Test Account 1' || a.Name == 'Test Account 6') {
                System.assertEquals('GOLD', a.Customer_Classification__c, 'Incorrect classification for ' + a.Name);
            } else if (a.Name == 'Test Account 2') {
                System.assertEquals('SILVER', a.Customer_Classification__c, 'Incorrect classification for ' + a.Name);
            } else if (a.Name == 'Test Account 3') {
                System.assertEquals('BRONZE', a.Customer_Classification__c, 'Incorrect classification for ' + a.Name);
            } else {
                System.assertEquals('', a.Customer_Classification__c, 'Incorrect classification for ' + a.Name);
            }
        }

        test.stopTest();
    }
}