lendinvest dev/force-app/main/default/objects/Account/fields/Customer_Classification__c.field-meta.xml
<CustomField>
    <fullName>Customer_Classification__c</fullName>
    <description>classifies the customer depending on total amount spent</description>
    <inlineHelpText>classifies the customer as follows: 
 ● GOLD = Total Customer Spend of £50,000 and above,
 ● SILVER = Total Customer Spend of £25,000 and above,
 ● BRONZE = Total Customer Spend of £10,000 and above, 
 ● &lt;blank&gt;= Total Customer Spend is less than £10,000, leave the field blank.</inlineHelpText>
    <label>Customer Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRONZE</fullName>
            </value>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>&apos;&apos;</fullName>
                <default>true</default>
                <label>&apos;&apos;</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

lendinvest dev/force-app/main/default/objects/Account/fields/First_Time_Gold_Classification__c.field-meta.xml
<CustomField>
    <fullName>First_Time_Gold_Classification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>flag to know if it s the first time that the account reach the gold classification</description>
    <inlineHelpText>flag to know if it s the first time that the account reach the gold classification</inlineHelpText>
    <label>First Time Gold Classification</label>
    <type>Checkbox</type>
</CustomField>

lendinvest dev/force-app/main/default/objects/Account/fields/Total_Customer_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Customer_Spend__c</fullName>
    <description>the Sum of the Amount of closed-won opportunities for an Account.</description>
    <inlineHelpText>this field display the Sum of the Amount of closed-won opportunities for an Account.</inlineHelpText>
    <label>Total Customer Spend</label>
    <summarizedField>Opportunity.Amount</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

lendinvest dev/force-app/main/default/classes/CustomerClassificationUtil.cls
/**
 * @description       : This class contains a utility method for updating the customer classification
 *                      for a list of accounts based on their Total_Customer_Spend__c field.
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 12-27-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class CustomerClassificationUtil {
    /**
     * Updates the customer classification for a list of accounts based on their Total_Customer_Spend__c field.
     * @param accounts A list of accounts to update.
     */
    public static void updateClassification(List<Account> accounts) {
        // Loop through the accounts and update their customer classification based on their Total_Customer_Spend__c field
        for (Account a : accounts) {
            if (a.Total_Customer_Spend__c >= 50000 && a.First_Time_Gold_Classification__c==false ) {
                a.Customer_Classification__c='GOLD';
                a.First_Time_Gold_Classification__c=true;
            } else if (a.Total_Customer_Spend__c >= 50000) {
                a.Customer_Classification__c='GOLD';
            }else if (a.Total_Customer_Spend__c >= 25000) {
                a.Customer_Classification__c='SILVER';
            } else if (a.Total_Customer_Spend__c >= 10000) {
                a.Customer_Classification__c='BRONZE';
            } else {
                a.Customer_Classification__c='';
            }
        }
    }
}